'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {taxonomy,type TaxonomyNode} from '@/lib/taxonomy';
import {kinds,slug,validateTaxonomy,previewSuggestions,type TaxonomyDocument} from '@/lib/taxonomy-editor';
import './taxonomy.css';
import {genreDescription} from '@/lib/genre-descriptions';
const key='mosaic-taxonomy-draft-v1';
const initial=():TaxonomyDocument=>({version:1,nodes:Object.fromEntries(Object.entries(structuredClone(taxonomy)).map(([id,n])=>[id,{...n,description:genreDescription(id)}]))});
const list=(s:string)=>[...new Set(s.split(',').map(slug).filter(Boolean))];
const name=(id:string,nodes:Record<string,TaxonomyNode>)=>nodes[id]?.label||id.replaceAll('-',' ');
export default function TaxonomyEditor(){
 const [doc,setDoc]=useState<TaxonomyDocument>(initial),[selected,setSelected]=useState('fantasy'),[form,setForm]=useState<TaxonomyNode>(()=>initial().nodes.fantasy),[newId,setNewId]=useState(''),[adding,setAdding]=useState(false),[q,setQ]=useState(''),[filter,setFilter]=useState('all'),[message,setMessage]=useState(''),[ready,setReady]=useState(false),[dirty,setDirty]=useState(false);
 const [previewTags,setPreviewTags]=useState('fantasy, magic'),[previewClass,setPreviewClass]=useState('fiction'),[previewMedia,setPreviewMedia]=useState('Book');
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const saved=JSON.parse(raw);const errors=validateTaxonomy(saved);if(errors.length)throw Error(errors[0]);setDoc(saved);setForm(saved.nodes.fantasy||taxonomy.fantasy);setMessage('Restored your saved browser draft.');}}catch{setMessage('Could not restore the browser draft. It has not been overwritten. Import a backup or save a new draft.');}setReady(true);},[]);
 function save(next:TaxonomyDocument){const errors=validateTaxonomy(next);if(errors.length){setMessage(errors.join(' '));return false;}try{localStorage.setItem(key,JSON.stringify(next));setDoc(next);setMessage('Draft saved in this browser. The public site is unchanged until this file is published.');return true;}catch{setMessage('Browser storage is unavailable. Export your draft before leaving.');setDoc(next);return true;}}
 function patch(change:Partial<TaxonomyNode>){setForm({...form,...change});setDirty(true);}
 function select(id:string){setSelected(id);setForm(structuredClone(doc.nodes[id]));setAdding(false);setDirty(false);setMessage('');}
 function submit(){const id=adding?slug(newId):selected;if(adding&&Object.hasOwn(doc.nodes,id)){setMessage('That stable ID already exists. Choose another.');return;}const clean={...form};for(const field of ['parents','classes','media','aliases'] as const){const values=[...new Set((clean[field]||[]).map(x=>x.trim()).filter(Boolean))];Object.assign(clean,{[field]:values.length?values:undefined});}const next={...doc,nodes:{...doc.nodes,[id]:clean}};if(save(next)){setForm(clean);setSelected(id);setAdding(false);setDirty(false);}}
 function download(){const blob=new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='mosaic-taxonomy-v1.json';a.click();URL.revokeObjectURL(url);}
 const related=Object.keys(doc.nodes).filter(id=>doc.nodes[id].parents?.includes(selected));
 const available=Object.keys(doc.nodes).filter(id=>(filter==='all'||doc.nodes[id].kind===filter)&&(name(id,doc.nodes)+' '+id).toLowerCase().includes(q.toLowerCase())).sort((a,b)=>name(a,doc.nodes).localeCompare(name(b,doc.nodes)));
 const hierarchy=['subgenre'].includes(form.kind),relationships=!['class','genre'].includes(form.kind),locked=['fiction','non-fiction'].includes(selected)&&!adding;
 const suggestions=previewSuggestions(doc.nodes,list(previewTags),previewMedia,previewClass);
 return <main className="taxonomy-editor">
  <Link href="/">← Back to Mosaic</Link><header><p className="eyebrow">Shape the connections</p><h1>Your taxonomy workshop</h1><p>Add tags, explain them in your own words, and organize where they fit. Save changes to your draft, then export it for publication.</p><p><strong>Draft only:</strong> this page does not edit the shared website or your library. The preview below reflects saved draft changes immediately.</p></header>
  <div role="status" aria-live="polite" className="notice">{message||'Choose a tag to edit. Stable IDs keep existing library tags connected when you change a display name.'}</div>
  <div className="workshop-grid"><aside aria-label="Find tags"><label>Search tags<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Try fantasy, tone or school"/></label><label>Tag type<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All types</option>{kinds.map(k=><option key={k}>{k}</option>)}</select></label><button disabled={!ready||dirty} onClick={()=>{setAdding(true);setNewId('');setForm({kind:'theme',description:'',label:''});setDirty(true);}}>+ Add a tag</button><p>{available.length} tags · archived tags remain recoverable</p><nav aria-label="Taxonomy tags">{available.map(id=><button key={id} disabled={dirty} aria-pressed={!adding&&selected===id} onClick={()=>select(id)}>{name(id,doc.nodes)}<small>{doc.nodes[id].kind}{doc.nodes[id].retired?' · archived':''}</small></button>)}</nav></aside>
  <section aria-label="Edit tag"><h2>{adding?'Add a tag':name(selected,doc.nodes)}</h2><p>Save or discard your changes before switching tags.</p><div className="field-grid">
   <label>Stable ID<input value={adding?newId:selected} disabled={!adding} onChange={e=>setNewId(e.target.value)} placeholder="e.g. coastal-mystery"/><small>Permanent reference. Rename using Display name instead.</small></label>
   <label>Display name<input value={form.label??name(selected,doc.nodes)} onChange={e=>patch({label:e.target.value})}/></label>
   <label>Tag type<select value={form.kind} disabled={locked} onChange={e=>patch({kind:e.target.value as TaxonomyNode['kind'],parents:undefined})}>{kinds.map(k=><option key={k}>{k}</option>)}</select><small>Genre: a broad story family. Subgenre: a more specific branch. Themes and tropes can overlap several branches.</small></label>
   <label>Aliases<input value={(form.aliases||[]).join(', ')} onChange={e=>patch({aliases:e.target.value.split(',').map(x=>x.trim())})}/><small>Other labels for the same concept, separated by commas. Publishing makes these equivalent in Week 8 cosine matching.</small></label>
  </div><label>Description<textarea rows={4} value={form.description} onChange={e=>patch({description:e.target.value})}/></label>
  {form.kind!=='class'&&<fieldset><legend>Content class</legend><p>Where is this label appropriate? Neither selected means either class, including unknown records.</p>{(['fiction','non-fiction'] as const).map(c=><label className="check" key={c}><input type="checkbox" checked={form.classes?.includes(c)||false} onChange={e=>patch({classes:e.target.checked?[...(form.classes||[]),c]:(form.classes||[]).filter(x=>x!==c)})}/>{c}</label>)}</fieldset>}
  {relationships&&<label>{hierarchy?'Belongs under':'Can apply to'}<input value={(form.parents||[]).join(', ')} onChange={e=>patch({parents:e.target.value.split(',').map(x=>x.trim())})} list="tag-ids"/><small>{hierarchy?'The broader branch this subgenre belongs to.':'Suggest this facet when a title has one of these genres or branches. This is a relevance hint, not proof the title has the tag.'} Use comma-separated stable IDs. Blank means no branch restriction.</small></label>}
  <datalist id="tag-ids">{Object.keys(doc.nodes).filter(id=>id!==selected&&!doc.nodes[id].retired).map(id=><option key={id} value={id}>{name(id,doc.nodes)}</option>)}</datalist>
  <fieldset><legend>Media applicability</legend><p>None selected means all media. This does not enable unsupported APIs.</p>{['Book','Movie','TV','Game','Music'].map(m=><label key={m} className="check"><input type="checkbox" checked={form.media?.includes(m)||false} onChange={e=>patch({media:e.target.checked?[...(form.media||[]),m]:(form.media||[]).filter(x=>x!==m)})}/>{m}</label>)}</fieldset>
  <div className="actions"><button disabled={!ready||!dirty} onClick={submit}>Save tag to draft</button><button disabled={!dirty} onClick={()=>select(selected)}>Discard unsaved changes</button></div>
  {!adding&&!locked&&<details><summary>Archive or restore this tag</summary><p>Archiving hides the tag from new suggestions and the glossary after publication. Existing item tags and scores retain their identity. Remove incoming relationships first.</p>{related.length>0&&<p>Referenced by: {related.join(', ')}</p>}<button disabled={dirty||(!form.retired&&related.some(id=>!doc.nodes[id].retired))} onClick={()=>{const next={...form,retired:!form.retired};if(save({...doc,nodes:{...doc.nodes,[selected]:next}}))setForm(next);}}>{form.retired?'Restore tag':'Archive tag'}</button></details>}
  </section></div>
  <section aria-label="Preview draft"><h2>Try your draft</h2><p>See which labels Mosaic would suggest for a title with these known tags. Suggestions are not automatically assigned to titles.</p><div className="field-grid"><label>Known tags<input value={previewTags} onChange={e=>setPreviewTags(e.target.value)}/></label><label>Content class<select value={previewClass} onChange={e=>setPreviewClass(e.target.value)}><option>fiction</option><option>non-fiction</option></select></label><label>Media<select value={previewMedia} onChange={e=>setPreviewMedia(e.target.value)}>{['Book','Movie','TV','Game','Music'].map(m=><option key={m}>{m}</option>)}</select></label></div><div className="chips">{suggestions.map(id=><span key={id} title={doc.nodes[id].description}>{name(id,doc.nodes)}</span>)}</div></section>
  <section><h2>Back up and publish</h2><p>Export saves all definitions, aliases and relationships. Import restores a draft; it does not publish. To update the shared site, apply the exported file to the repository, test it and deploy. New labels still need source metadata or manual assignment; the editor does not create new API search or synopsis rules.</p><div className="actions"><button disabled={dirty||!ready} onClick={download}>Export draft JSON</button><label>Import draft JSON<input type="file" accept="application/json,.json" disabled={dirty||!ready} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>2000000)throw Error('File must be smaller than 2 MB.');const next=JSON.parse(await file.text());if(save(next)){const id=Object.keys(next.nodes)[0];if(id){setSelected(id);setForm(next.nodes[id]);setAdding(false);}}}catch(error){setMessage(error instanceof Error?error.message:'Invalid JSON file.');}e.target.value='';}}/></label></div><p>Existing library records are never deleted by this editor. Keep exported backups before importing a replacement draft.</p></section>
 </main>;
}
