import type { Media } from './recommendations';
// Hand-authored demonstration metadata, not authoritative classifications.
const rows = [
  [
    'hunger',
    'The Hunger Games',
    'Suzanne Collins',
    'Book',
    'survival rebellion dystopian emotional',
    'A young volunteer challenges a society built around a fight for survival.',
  ],
  [
    'earthsea',
    'A Wizard of Earthsea',
    'Ursula K. Le Guin',
    'Book',
    'fantasy identity adventure reflective',
    'A young wizard learns the cost of power and the meaning of knowing himself.',
  ],
  [
    'station',
    'Station Eleven',
    'Emily St. John Mandel',
    'Book',
    'survival connection emotional reflective',
    'Art and human connection endure in a world reshaped by a pandemic.',
  ],
  [
    'pride',
    'Pride and Prejudice',
    'Jane Austen',
    'Book',
    'romance identity humor connection',
    'First impressions and social expectations complicate an unlikely romance.',
  ],
  [
    'hobbit',
    'The Hobbit',
    'J. R. R. Tolkien',
    'Book',
    'fantasy adventure friendship hope',
    'An unassuming traveler finds courage on a journey far from home.',
  ],
  [
    'last',
    'The Last of Us',
    'Naughty Dog',
    'Game',
    'survival emotional connection adventure',
    'Two survivors form an uneasy bond on a dangerous journey.',
  ],
  [
    'life',
    'Life Is Strange',
    'Dontnod Entertainment',
    'Game',
    'identity emotional friendship mystery',
    'A student discovers that changing time comes with difficult choices.',
  ],
  [
    'journey',
    'Journey',
    'thatgamecompany',
    'Game',
    'adventure reflective connection hope',
    'A quiet pilgrimage unfolds through an ancient desert landscape.',
  ],
  [
    'hades',
    'Hades',
    'Supergiant Games',
    'Game',
    'fantasy rebellion adventure identity',
    'An underworld prince battles toward freedom and family answers.',
  ],
  [
    'stardew',
    'Stardew Valley',
    'ConcernedApe',
    'Game',
    'connection hope romance reflective',
    'Build a new life through farming, friendship, and a small community.',
  ],
  [
    'interstellar',
    'Interstellar',
    'Christopher Nolan',
    'Movie',
    'adventure survival emotional hope',
    'A journey beyond Earth tests the bonds between a parent and child.',
  ],
  [
    'spirited',
    'Spirited Away',
    'Hayao Miyazaki',
    'Movie',
    'fantasy identity adventure friendship',
    'A girl finds her courage in a mysterious world of spirits.',
  ],
  [
    'arrival',
    'Arrival',
    'Denis Villeneuve',
    'Movie',
    'mystery connection reflective emotional',
    'A linguist seeks understanding when visitors arrive from another world.',
  ],
  [
    'truman',
    'The Truman Show',
    'Peter Weir',
    'Movie',
    'identity rebellion mystery hope',
    'An ordinary man begins to question the world built around him.',
  ],
  [
    'amelie',
    'Amélie',
    'Jean-Pierre Jeunet',
    'Movie',
    'romance connection humor hope',
    'Small acts of kindness lead a shy Parisian toward connection.',
  ],
  [
    'stranger',
    'Stranger Things',
    'The Duffer Brothers',
    'TV',
    'mystery friendship survival adventure',
    'Friends investigate strange events beneath the surface of their town.',
  ],
  [
    'severance',
    'Severance',
    'Dan Erickson',
    'TV',
    'identity dystopian mystery rebellion',
    'Workers uncover the consequences of dividing their lives in two.',
  ],
  [
    'goodplace',
    'The Good Place',
    'Michael Schur',
    'TV',
    'humor friendship reflective hope',
    'An unlikely group explores what it means to become better people.',
  ],
  [
    'avatar',
    'Avatar: The Last Airbender',
    'DiMartino & Konietzko',
    'TV',
    'fantasy adventure friendship hope',
    'Young companions set out to restore balance to a divided world.',
  ],
  [
    'arcane',
    'Arcane',
    'Christian Linke & Alex Yee',
    'TV',
    'rebellion emotional fantasy identity',
    'Two sisters are pulled apart by conflict between connected cities.',
  ],
  [
    'folklore',
    'folklore',
    'Taylor Swift · Album',
    'Music',
    'reflective emotional romance connection',
    'Intimate storytelling explores memory, longing, and imagined lives.',
  ],
  [
    'resistance',
    'The Resistance',
    'Muse · Album',
    'Music',
    'rebellion dystopian romance hope',
    'Dramatic rock moves through resistance, control, and devotion.',
  ],
  [
    'melodrama',
    'Melodrama',
    'Lorde · Album',
    'Music',
    'identity emotional romance reflective',
    'A vivid portrait of heartbreak, independence, and growing into yourself.',
  ],
  [
    'nurture',
    'Nurture',
    'Porter Robinson · Album',
    'Music',
    'hope reflective identity connection',
    'Electronic songwriting searches for renewal and creative purpose.',
  ],
  [
    'boniver',
    'For Emma, Forever Ago',
    'Bon Iver · Album',
    'Music',
    'emotional reflective romance survival',
    'Sparse folk songs trace isolation, loss, and emotional recovery.',
  ],
];
export const catalog: Media[] = rows.map(
  ([id, title, creator, type, tags, description]) => ({
    id,
    title,
    creator,
    type: type as Media['type'],
    tags: tags.split(' '),
    description,
  }),
);
